// Copied from stringi 19e9586ba39b3320df49355e32bd18d74ed6098f; stri_* renamed to ci_*. See inst/COPYRIGHTS.
/* This file is part of the 'stringi' project.
 * Copyright (c) 2013-2025, Marek Gagolewski <https://www.gagolewski.com/>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#include <R.h>
#include <Rconfig.h>
#include <Rversion.h>
#include <R_ext/Rdynload.h>

#include "../altrep_backend/ci_exports.h"
#include "../base/charr_base.h"
#include "../charr_icu.h"


#define STRI__MK_CALL(symb, name, args) \
   {symb, (DL_FUNC)(void (*) (void))(&name), args}


/**
 * List of functions available via .Call() in R
 *
 * Form:
 * \code{\{"method_name", (DL_FUNC)pointer, number_of_args\}} -
 * this is generated by the STRI__MK_CALL macro.
 */
const R_CallMethodDef cCallMethods[] = {
    STRI__MK_CALL("C_ci_cmp_eq",                       ci_cmp_eq,                     2),
    STRI__MK_CALL("C_ci_cmp_neq",                      ci_cmp_neq,                    2),
    STRI__MK_CALL("C_ci_cmp",                          ci_cmp,                        3),
    STRI__MK_CALL("C_ci_cmp_lt",                       ci_cmp_lt,                     3),
    STRI__MK_CALL("C_ci_cmp_le",                       ci_cmp_le,                     3),
    STRI__MK_CALL("C_ci_cmp_gt",                       ci_cmp_gt,                     3),
    STRI__MK_CALL("C_ci_cmp_ge",                       ci_cmp_ge,                     3),
    STRI__MK_CALL("C_ci_cmp_equiv",                    ci_cmp_equiv,                  3),
    STRI__MK_CALL("C_ci_cmp_nequiv",                   ci_cmp_nequiv,                 3),
    STRI__MK_CALL("C_ci_count_boundaries",             ci_count_boundaries,           2),
    STRI__MK_CALL("C_ci_count_fixed",                  ci_count_fixed,                3),
    STRI__MK_CALL("C_ci_count_coll",                   ci_count_coll,                 3),
    STRI__MK_CALL("C_ci_count_regex",                  ci_count_regex,                3),
    STRI__MK_CALL("C_ci_detect_coll",                  ci_detect_coll,                5),
    STRI__MK_CALL("C_ci_detect_fixed",                 ci_detect_fixed,               5),
    STRI__MK_CALL("C_ci_detect_regex",                 ci_detect_regex,               5),
    STRI__MK_CALL("C_ci_dup",                          ci_dup,                        2),
    STRI__MK_CALL("C_ci_duplicated",                   ci_duplicated,                 3),
    STRI__MK_CALL("C_ci_duplicated_any",               ci_duplicated_any,             3),
    STRI__MK_CALL("C_ci_enc_info",                     ci_enc_info,                   1),
    STRI__MK_CALL("C_ci_enc_mark",                     ci_enc_mark,                   1),
    STRI__MK_CALL("C_ci_enc_fromutf32",                ci_enc_fromutf32,              1),
    STRI__MK_CALL("C_ci_enc_toascii",                  ci_enc_toascii,                1),
    STRI__MK_CALL("C_ci_enc_toutf8",                   ci_enc_toutf8,                 3),
    STRI__MK_CALL("C_ci_enc_toutf32",                  ci_enc_toutf32,                1),
    STRI__MK_CALL("C_ci_encode",                       ci_encode,                     4),
    STRI__MK_CALL("C_ci_endswith_coll",                ci_endswith_coll,              5),
    STRI__MK_CALL("C_ci_endswith_fixed",               ci_endswith_fixed,             5),
    STRI__MK_CALL("C_ci_escape_unicode",               ci_escape_unicode,             1),
    STRI__MK_CALL("C_ci_extract_first_boundaries",     ci_extract_first_boundaries,   2),
    STRI__MK_CALL("C_ci_extract_last_boundaries",      ci_extract_last_boundaries,    2),
    STRI__MK_CALL("C_ci_extract_all_boundaries",       ci_extract_all_boundaries,     4),
    STRI__MK_CALL("C_ci_extract_first_coll",           ci_extract_first_coll,         3),
    STRI__MK_CALL("C_ci_extract_last_coll",            ci_extract_last_coll,          3),
    STRI__MK_CALL("C_ci_extract_all_coll",             ci_extract_all_coll,           5),
    STRI__MK_CALL("C_ci_extract_first_fixed",          ci_extract_first_fixed,        3),
    STRI__MK_CALL("C_ci_extract_last_fixed",           ci_extract_last_fixed,         3),
    STRI__MK_CALL("C_ci_extract_all_fixed",            ci_extract_all_fixed,          5),
    STRI__MK_CALL("C_ci_extract_first_regex",          ci_extract_first_regex,        3),
    STRI__MK_CALL("C_ci_extract_last_regex",           ci_extract_last_regex,         3),
    STRI__MK_CALL("C_ci_extract_all_regex",            ci_extract_all_regex,          5),
    STRI__MK_CALL("C_ci_flatten",                      ci_flatten,                    4),
    STRI__MK_CALL("C_ci_join",                         ci_join,                       4),
    STRI__MK_CALL("C_ci_join_list",                    ci_join_list,                  3),
    STRI__MK_CALL("C_ci_length",                       ci_length,                     1),
    STRI__MK_CALL("C_ci_locate_all_boundaries",        ci_locate_all_boundaries,      4),
    STRI__MK_CALL("C_ci_locate_first_boundaries",      ci_locate_first_boundaries,    3),
    STRI__MK_CALL("C_ci_locate_last_boundaries",       ci_locate_last_boundaries,     3),
    STRI__MK_CALL("C_ci_locate_first_fixed",           ci_locate_first_fixed,         4),
    STRI__MK_CALL("C_ci_locate_all_fixed",             ci_locate_all_fixed,           5),
    STRI__MK_CALL("C_ci_locate_last_coll",             ci_locate_last_coll,           4),
    STRI__MK_CALL("C_ci_locate_first_coll",            ci_locate_first_coll,          4),
    STRI__MK_CALL("C_ci_locate_all_coll",              ci_locate_all_coll,            5),
    STRI__MK_CALL("C_ci_locate_all_regex",             ci_locate_all_regex,           6),
    STRI__MK_CALL("C_ci_locate_first_regex",           ci_locate_first_regex,         5),
    STRI__MK_CALL("C_ci_locate_last_regex",            ci_locate_last_regex,          5),
    STRI__MK_CALL("C_ci_match_first_regex",            ci_match_first_regex,          4),
    STRI__MK_CALL("C_ci_match_last_regex",             ci_match_last_regex,           4),
    STRI__MK_CALL("C_ci_match_all_regex",              ci_match_all_regex,            5),
    STRI__MK_CALL("C_ci_order",                        ci_order,                      4),
    STRI__MK_CALL("C_ci_rank",                         ci_rank,                       2),
    STRI__MK_CALL("C_ci_sort",                         ci_sort,                       4),
    STRI__MK_CALL("C_ci_sort_key",                     ci_sort_key,                   2),
    STRI__MK_CALL("C_ci_pad",                          ci_pad,                        5),
    STRI__MK_CALL("C_ci_replace_na",                   ci_replace_na,                 2),
    STRI__MK_CALL("C_ci_replace_all_fixed",            ci_replace_all_fixed,          5),
    STRI__MK_CALL("C_ci_replace_first_fixed",          ci_replace_first_fixed,        4),
    STRI__MK_CALL("C_ci_replace_last_fixed",           ci_replace_last_fixed,         4),
    STRI__MK_CALL("C_ci_replace_all_coll",             ci_replace_all_coll,           5),
    STRI__MK_CALL("C_ci_replace_first_coll",           ci_replace_first_coll,         4),
    STRI__MK_CALL("C_ci_replace_last_coll",            ci_replace_last_coll,          4),
    STRI__MK_CALL("C_ci_replace_all_regex",            ci_replace_all_regex,          5),
    STRI__MK_CALL("C_ci_replace_first_regex",          ci_replace_first_regex,        4),
    STRI__MK_CALL("C_ci_replace_last_regex",           ci_replace_last_regex,         4),
    STRI__MK_CALL("C_ci_replace_all_charclass",        ci_replace_all_charclass,      5),
    STRI__MK_CALL("C_ci_reverse",                      ci_reverse,                    1),
    STRI__MK_CALL("C_ci_read_lines",                   ci_read_lines,                 2),
    STRI__MK_CALL("C_ci_split_boundaries",             ci_split_boundaries,           5),
    STRI__MK_CALL("C_ci_split_coll",                   ci_split_coll,                 7),
    STRI__MK_CALL("C_ci_split_fixed",                  ci_split_fixed,                7),
    STRI__MK_CALL("C_ci_split_lines",                  ci_split_lines,                2),
    STRI__MK_CALL("C_ci_split_lines1",                 ci_split_lines1,               1),
    STRI__MK_CALL("C_ci_split_regex",                  ci_split_regex,                7),
    STRI__MK_CALL("C_ci_startswith_coll",              ci_startswith_coll,            5),
    STRI__MK_CALL("C_ci_startswith_fixed",             ci_startswith_fixed,           5),
    STRI__MK_CALL("C_ci_sub",                          ci_sub,                        6),
    STRI__MK_CALL("C_ci_sub_all",                      ci_sub_all,                    6),
    STRI__MK_CALL("C_ci_sub_replacement",              ci_sub_replacement,            7),
    STRI__MK_CALL("C_ci_sub_replacement_all",          ci_sub_replacement_all,        7),
    STRI__MK_CALL("C_ci_subset_coll",                  ci_subset_coll,                5),
    STRI__MK_CALL("C_ci_subset_regex",                 ci_subset_regex,               5),
    STRI__MK_CALL("C_ci_test_erroring_altrep",         ci_test_erroring_altrep,        1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer16b",     ci_test_UnicodeContainer16b,   1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer8b",      ci_test_UnicodeContainer8b,    1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer8_alias", ci_test_UnicodeContainer8_alias, 1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer8_independent", ci_test_UnicodeContainer8_independent, 1),
    STRI__MK_CALL("C_ci_test_ByteSearchContainer",     ci_test_ByteSearchContainer,   1),
    STRI__MK_CALL("C_ci_test_ByteSearchContainer_error", ci_test_ByteSearchContainer_error, 1),
    STRI__MK_CALL("C_ci_test_ByteSearchMatcher",       ci_test_ByteSearchMatcher,     3),
    STRI__MK_CALL("C_ci_test_Utf8Record_views",       ci_test_Utf8Record_views,     0),
    STRI__MK_CALL("C_ci_test_UTF8EncodingMarks",      ci_test_UTF8EncodingMarks,    0),
    STRI__MK_CALL("C_ci_test_ListUTF8",                ci_test_ListUTF8,              2),
    STRI__MK_CALL("C_ci_trans_nfc",                    ci_trans_nfc,                  1),
    STRI__MK_CALL("C_ci_trans_totitle",                ci_trans_totitle,              2),
    STRI__MK_CALL("C_ci_trans_tolower",                ci_trans_tolower,              2),
    STRI__MK_CALL("C_ci_trans_toupper",                ci_trans_toupper,              2),
    STRI__MK_CALL("C_ci_trans_casefold",               ci_trans_casefold,             1),
    STRI__MK_CALL("C_ci_trim_both",                    ci_trim_both,                  3),
    STRI__MK_CALL("C_ci_trim_left",                    ci_trim_left,                  3),
    STRI__MK_CALL("C_ci_trim_right",                   ci_trim_right,                 3),
    STRI__MK_CALL("C_ci_unescape_unicode",             ci_unescape_unicode,           1),
    STRI__MK_CALL("C_ci_unique",                       ci_unique,                     2),
    STRI__MK_CALL("C_ci_width",                        ci_width,                      1),
    STRI__MK_CALL("C_ci_wrap",                         ci_wrap,                      12),
    #define CHARR_BASE_REGISTER(name, arity) \
        STRI__MK_CALL("C_charr_base_" #name, C_charr_base_##name, arity),
    CHARR_BASE_NATIVE_METHODS(CHARR_BASE_REGISTER)
    #undef CHARR_BASE_REGISTER
    // the list must be NULL-terminated:
    STRI__MK_CALL("C_charr_abi_ok",                     C_charr_abi_ok,                   0),
    STRI__MK_CALL("C_charr_icu_init",                   C_charr_icu_init,                 1),
    STRI__MK_CALL("C_charr_icu_info",                   C_charr_icu_info,                 0),
    STRI__MK_CALL("C_charr_icu_version",                C_charr_icu_version,              0),
    STRI__MK_CALL("C_charr_icu_ok",                     C_charr_icu_ok,                   0),
    STRI__MK_CALL("C_charr_icu_smoke",                  C_charr_icu_smoke,                0),
    STRI__MK_CALL("C_charr_icu_bundled",                C_charr_icu_bundled,              0),
    {NULL,                           NULL,                  0}

};


/**
 * Library initialization.
 *
 * R calls this automatically on lib load/attach.
 */
extern "C" void R_init_charr(DllInfo* dll)
{
    R_registerRoutines(dll, NULL, cCallMethods, NULL, NULL);
    R_useDynamicSymbols(dll, (Rboolean)FALSE);
#if defined(R_VERSION) && R_VERSION >= R_Version(3, 0, 0)
    R_forceSymbols(dll, (Rboolean)TRUE);
#endif

    ci_test_init_erroring_altrep(dll);

    if (!SUPPORT_UTF8) {
        /* Rconfig.h states that all R platforms support that */
        Rf_error("R does not support UTF-8 encoding.");
    }
}


// There is no package-unload cleanup hook. A system ICU is process-global and
// may be in use by R or another package, so charr must not call u_cleanup().
