// Copied from stringi 19e9586ba39b3320df49355e32bd18d74ed6098f; stri_* renamed to ci_*. See inst/COPYRIGHTS.
/* This file is part of the 'stringi' project.
 * Copyright (c) 2013-2025, Marek Gagolewski <https://www.gagolewski.com/>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#include "ci_stringi.h"
#include "../charr_icu.h"
#include "ci_callables.h"
#include <cstring>
#include <cstdlib>
#include <unicode/uclean.h>

#ifndef STRI_ICU_FOUND
#include "uconfig_local.h"
#endif


#define STRI__MK_CALL(symb, name, args) \
   {symb, (DL_FUNC)(void (*) (void))(&name), args}


/**
 * List of functions available via .Call() in R
 *
 * Form:
 * \code{\{"method_name", (DL_FUNC)pointer, number_of_args\}} -
 * this is generated by the STRI__MK_CALL macro.
 */
const R_CallMethodDef cCallMethods[] = {
// STRI__MK_CALL("C_ci_c_posixst",                    ci_c_posixst,                  1),  // internal
    STRI__MK_CALL("C_ci_cmp_eq",                       ci_cmp_eq,                     2),
    STRI__MK_CALL("C_ci_cmp_neq",                      ci_cmp_neq,                    2),
    STRI__MK_CALL("C_ci_cmp",                          ci_cmp,                        3),
    STRI__MK_CALL("C_ci_cmp_lt",                       ci_cmp_lt,                     3),
    STRI__MK_CALL("C_ci_cmp_le",                       ci_cmp_le,                     3),
    STRI__MK_CALL("C_ci_cmp_gt",                       ci_cmp_gt,                     3),
    STRI__MK_CALL("C_ci_cmp_ge",                       ci_cmp_ge,                     3),
    STRI__MK_CALL("C_ci_cmp_equiv",                    ci_cmp_equiv,                  3),
    STRI__MK_CALL("C_ci_cmp_nequiv",                   ci_cmp_nequiv,                 3),
    STRI__MK_CALL("C_ci_count_boundaries",             ci_count_boundaries,           2),
    STRI__MK_CALL("C_ci_count_charclass",              ci_count_charclass,            2),
    STRI__MK_CALL("C_ci_count_fixed",                  ci_count_fixed,                3),
    STRI__MK_CALL("C_ci_count_coll",                   ci_count_coll,                 3),
    STRI__MK_CALL("C_ci_count_regex",                  ci_count_regex,                3),
    STRI__MK_CALL("C_ci_datetime_symbols",             ci_datetime_symbols,           3),
    STRI__MK_CALL("C_ci_datetime_fields",              ci_datetime_fields,            3),
    STRI__MK_CALL("C_ci_datetime_fstr",                ci_datetime_fstr,              1),
    STRI__MK_CALL("C_ci_datetime_now",                 ci_datetime_now,               0),
    STRI__MK_CALL("C_ci_datetime_create",              ci_datetime_create,            9),
    STRI__MK_CALL("C_ci_datetime_format",              ci_datetime_format,            4),
    STRI__MK_CALL("C_ci_datetime_parse",               ci_datetime_parse,             5),
    STRI__MK_CALL("C_ci_datetime_add",                 ci_datetime_add,               5),
    STRI__MK_CALL("C_ci_detect_charclass",             ci_detect_charclass,           4),
    STRI__MK_CALL("C_ci_detect_coll",                  ci_detect_coll,                5),
    STRI__MK_CALL("C_ci_detect_fixed",                 ci_detect_fixed,               5),
    STRI__MK_CALL("C_ci_detect_regex",                 ci_detect_regex,               5),
    STRI__MK_CALL("C_ci_dup",                          ci_dup,                        2),
    STRI__MK_CALL("C_ci_duplicated",                   ci_duplicated,                 3),
    STRI__MK_CALL("C_ci_duplicated_any",               ci_duplicated_any,             3),
    STRI__MK_CALL("C_ci_enc_detect",                   ci_enc_detect,                 2),
    STRI__MK_CALL("C_ci_enc_detect2",                  ci_enc_detect2,                2),
    STRI__MK_CALL("C_ci_enc_isutf8",                   ci_enc_isutf8,                 1),
    STRI__MK_CALL("C_ci_enc_isutf16le",                ci_enc_isutf16le,              1),
    STRI__MK_CALL("C_ci_enc_isutf16be",                ci_enc_isutf16be,              1),
    STRI__MK_CALL("C_ci_enc_isutf32le",                ci_enc_isutf32le,              1),
    STRI__MK_CALL("C_ci_enc_isutf32be",                ci_enc_isutf32be,              1),
    STRI__MK_CALL("C_ci_enc_isascii",                  ci_enc_isascii,                1),
    STRI__MK_CALL("C_ci_enc_info",                     ci_enc_info,                   1),
    STRI__MK_CALL("C_ci_enc_list",                     ci_enc_list,                   0),
    STRI__MK_CALL("C_ci_enc_mark",                     ci_enc_mark,                   1),
    STRI__MK_CALL("C_ci_enc_set",                      ci_enc_set,                    1),
    STRI__MK_CALL("C_ci_enc_fromutf32",                ci_enc_fromutf32,              1),
    STRI__MK_CALL("C_ci_enc_toascii",                  ci_enc_toascii,                1),
    STRI__MK_CALL("C_ci_enc_toutf8",                   ci_enc_toutf8,                 3),
    STRI__MK_CALL("C_ci_enc_toutf32",                  ci_enc_toutf32,                1),
    STRI__MK_CALL("C_ci_encode",                       ci_encode,                     4),
    STRI__MK_CALL("C_ci_endswith_charclass",           ci_endswith_charclass,         4),
    STRI__MK_CALL("C_ci_endswith_coll",                ci_endswith_coll,              5),
    STRI__MK_CALL("C_ci_endswith_fixed",               ci_endswith_fixed,             5),
    STRI__MK_CALL("C_ci_escape_unicode",               ci_escape_unicode,             1),
    STRI__MK_CALL("C_ci_extract_first_boundaries",     ci_extract_first_boundaries,   2),
    STRI__MK_CALL("C_ci_extract_last_boundaries",      ci_extract_last_boundaries,    2),
    STRI__MK_CALL("C_ci_extract_all_boundaries",       ci_extract_all_boundaries,     4),
    STRI__MK_CALL("C_ci_extract_first_charclass",      ci_extract_first_charclass,    2),
    STRI__MK_CALL("C_ci_extract_last_charclass",       ci_extract_last_charclass,     2),
    STRI__MK_CALL("C_ci_extract_all_charclass",        ci_extract_all_charclass,      5),
    STRI__MK_CALL("C_ci_extract_first_coll",           ci_extract_first_coll,         3),
    STRI__MK_CALL("C_ci_extract_last_coll",            ci_extract_last_coll,          3),
    STRI__MK_CALL("C_ci_extract_all_coll",             ci_extract_all_coll,           5),
    STRI__MK_CALL("C_ci_extract_first_fixed",          ci_extract_first_fixed,        3),
    STRI__MK_CALL("C_ci_extract_last_fixed",           ci_extract_last_fixed,         3),
    STRI__MK_CALL("C_ci_extract_all_fixed",            ci_extract_all_fixed,          5),
    STRI__MK_CALL("C_ci_extract_first_regex",          ci_extract_first_regex,        3),
    STRI__MK_CALL("C_ci_extract_last_regex",           ci_extract_last_regex,         3),
    STRI__MK_CALL("C_ci_extract_all_regex",            ci_extract_all_regex,          5),
    STRI__MK_CALL("C_ci_flatten",                      ci_flatten,                    4),
    STRI__MK_CALL("C_ci_info",                         ci_info,                       0),
    STRI__MK_CALL("C_ci_isempty",                      ci_isempty,                    1),
    STRI__MK_CALL("C_ci_join",                         ci_join,                       4),
    STRI__MK_CALL("C_ci_join_list",                    ci_join_list,                  3),
    STRI__MK_CALL("C_ci_join2",                        ci_join2,                      2),
    STRI__MK_CALL("C_ci_length",                       ci_length,                     1),
    STRI__MK_CALL("C_ci_list2matrix",                  ci_list2matrix,                4),
    STRI__MK_CALL("C_ci_locale_info",                  ci_locale_info,                1),
    STRI__MK_CALL("C_ci_locale_list",                  ci_locale_list,                0),
    STRI__MK_CALL("C_ci_locale_set",                   ci_locale_set,                 1),
    STRI__MK_CALL("C_ci_locate_all_boundaries",        ci_locate_all_boundaries,      4),
    STRI__MK_CALL("C_ci_locate_first_boundaries",      ci_locate_first_boundaries,    3),
    STRI__MK_CALL("C_ci_locate_last_boundaries",       ci_locate_last_boundaries,     3),
    STRI__MK_CALL("C_ci_locate_first_charclass",       ci_locate_first_charclass,     3),
    STRI__MK_CALL("C_ci_locate_last_charclass",        ci_locate_last_charclass,      3),
    STRI__MK_CALL("C_ci_locate_all_charclass",         ci_locate_all_charclass,       5),
    STRI__MK_CALL("C_ci_locate_last_fixed",            ci_locate_last_fixed,          4),
    STRI__MK_CALL("C_ci_locate_first_fixed",           ci_locate_first_fixed,         4),
    STRI__MK_CALL("C_ci_locate_all_fixed",             ci_locate_all_fixed,           5),
    STRI__MK_CALL("C_ci_locate_last_coll",             ci_locate_last_coll,           4),
    STRI__MK_CALL("C_ci_locate_first_coll",            ci_locate_first_coll,          4),
    STRI__MK_CALL("C_ci_locate_all_coll",              ci_locate_all_coll,            5),
    STRI__MK_CALL("C_ci_locate_all_regex",             ci_locate_all_regex,           6),
    STRI__MK_CALL("C_ci_locate_first_regex",           ci_locate_first_regex,         5),
    STRI__MK_CALL("C_ci_locate_last_regex",            ci_locate_last_regex,          5),
    STRI__MK_CALL("C_ci_match_first_regex",            ci_match_first_regex,          4),
    STRI__MK_CALL("C_ci_match_last_regex",             ci_match_last_regex,           4),
    STRI__MK_CALL("C_ci_match_all_regex",              ci_match_all_regex,            5),
    STRI__MK_CALL("C_ci_numbytes",                     ci_numbytes,                   1),
    STRI__MK_CALL("C_ci_order",                        ci_order,                      4),
    STRI__MK_CALL("C_ci_rank",                         ci_rank,                       2),
    STRI__MK_CALL("C_ci_sort",                         ci_sort,                       4),
    STRI__MK_CALL("C_ci_sort_key",                     ci_sort_key,                   2),
    STRI__MK_CALL("C_ci_pad",                          ci_pad,                        5),
    STRI__MK_CALL("C_ci_prepare_arg_string",           ci_prepare_arg_string,         2),
    STRI__MK_CALL("C_ci_prepare_arg_double",           ci_prepare_arg_double,         2),
    STRI__MK_CALL("C_ci_prepare_arg_integer",          ci_prepare_arg_integer,        2),
    STRI__MK_CALL("C_ci_prepare_arg_logical",          ci_prepare_arg_logical,        2),
    STRI__MK_CALL("C_ci_prepare_arg_raw",              ci_prepare_arg_raw,            2),
    STRI__MK_CALL("C_ci_prepare_arg_string_1",         ci_prepare_arg_string_1,       2),
    STRI__MK_CALL("C_ci_prepare_arg_double_1",         ci_prepare_arg_double_1,       2),
    STRI__MK_CALL("C_ci_prepare_arg_integer_1",        ci_prepare_arg_integer_1,      2),
    STRI__MK_CALL("C_ci_prepare_arg_logical_1",        ci_prepare_arg_logical_1,      2),
    STRI__MK_CALL("C_ci_rand_shuffle",                 ci_rand_shuffle,               1),
    STRI__MK_CALL("C_ci_rand_strings",                 ci_rand_strings,               3),
    STRI__MK_CALL("C_ci_replace_na",                   ci_replace_na,                 2),
    STRI__MK_CALL("C_ci_replace_rstr",                 ci_replace_rstr,               1),
    STRI__MK_CALL("C_ci_replace_all_fixed",            ci_replace_all_fixed,          5),
    STRI__MK_CALL("C_ci_replace_first_fixed",          ci_replace_first_fixed,        4),
    STRI__MK_CALL("C_ci_replace_last_fixed",           ci_replace_last_fixed,         4),
    STRI__MK_CALL("C_ci_replace_all_coll",             ci_replace_all_coll,           5),
    STRI__MK_CALL("C_ci_replace_first_coll",           ci_replace_first_coll,         4),
    STRI__MK_CALL("C_ci_replace_last_coll",            ci_replace_last_coll,          4),
    STRI__MK_CALL("C_ci_replace_all_regex",            ci_replace_all_regex,          5),
    STRI__MK_CALL("C_ci_replace_first_regex",          ci_replace_first_regex,        4),
    STRI__MK_CALL("C_ci_replace_last_regex",           ci_replace_last_regex,         4),
    STRI__MK_CALL("C_ci_replace_all_charclass",        ci_replace_all_charclass,      5),
    STRI__MK_CALL("C_ci_replace_first_charclass",      ci_replace_first_charclass,    3),
    STRI__MK_CALL("C_ci_replace_last_charclass",       ci_replace_last_charclass,     3),
    STRI__MK_CALL("C_ci_reverse",                      ci_reverse,                    1),
    STRI__MK_CALL("C_ci_split_boundaries",             ci_split_boundaries,           5),
    STRI__MK_CALL("C_ci_split_charclass",              ci_split_charclass,            6),
    STRI__MK_CALL("C_ci_split_coll",                   ci_split_coll,                 7),
    STRI__MK_CALL("C_ci_split_fixed",                  ci_split_fixed,                7),
    STRI__MK_CALL("C_ci_split_lines",                  ci_split_lines,                2),
    STRI__MK_CALL("C_ci_split_lines1",                 ci_split_lines1,               1),
    STRI__MK_CALL("C_ci_split_regex",                  ci_split_regex,                7),
    STRI__MK_CALL("C_ci_sprintf",                      ci_sprintf,                    6),
    STRI__MK_CALL("C_ci_startswith_charclass",         ci_startswith_charclass,       4),
    STRI__MK_CALL("C_ci_startswith_coll",              ci_startswith_coll,            5),
    STRI__MK_CALL("C_ci_startswith_fixed",             ci_startswith_fixed,           5),
    STRI__MK_CALL("C_ci_stats_general",                ci_stats_general,              1),
    STRI__MK_CALL("C_ci_stats_latex",                  ci_stats_latex,                1),
    STRI__MK_CALL("C_ci_sub",                          ci_sub,                        6),
    STRI__MK_CALL("C_ci_sub_all",                      ci_sub_all,                    6),
    STRI__MK_CALL("C_ci_sub_replacement",              ci_sub_replacement,            7),
    STRI__MK_CALL("C_ci_sub_replacement_all",          ci_sub_replacement_all,        7),
    STRI__MK_CALL("C_ci_subset_charclass",             ci_subset_charclass,           4),
    STRI__MK_CALL("C_ci_subset_coll",                  ci_subset_coll,                5),
    STRI__MK_CALL("C_ci_subset_fixed",                 ci_subset_fixed,               5),
    STRI__MK_CALL("C_ci_subset_regex",                 ci_subset_regex,               5),
    STRI__MK_CALL("C_ci_subset_charclass_replacement", ci_subset_charclass_replacement, 4),
    STRI__MK_CALL("C_ci_subset_coll_replacement",      ci_subset_coll_replacement,    5),
    STRI__MK_CALL("C_ci_subset_fixed_replacement",     ci_subset_fixed_replacement,   5),
    STRI__MK_CALL("C_ci_subset_regex_replacement",     ci_subset_regex_replacement,   5),
    STRI__MK_CALL("C_ci_test_erroring_altrep",         ci_test_erroring_altrep,        1),
    STRI__MK_CALL("C_ci_test_Rmark",                   ci_test_Rmark,                 1),
    STRI__MK_CALL("C_ci_test_returnasis",              ci_test_returnasis,            1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer16",      ci_test_UnicodeContainer16,    1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer16b",     ci_test_UnicodeContainer16b,   1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer8",       ci_test_UnicodeContainer8,     1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer8b",      ci_test_UnicodeContainer8b,    1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer8_alias", ci_test_UnicodeContainer8_alias, 1),
    STRI__MK_CALL("C_ci_test_UnicodeContainer8_independent", ci_test_UnicodeContainer8_independent, 1),
    STRI__MK_CALL("C_ci_test_ByteSearchContainer",     ci_test_ByteSearchContainer,   1),
    STRI__MK_CALL("C_ci_test_ByteSearchContainer_error", ci_test_ByteSearchContainer_error, 1),
    STRI__MK_CALL("C_ci_test_ByteSearchMatcher",       ci_test_ByteSearchMatcher,     3),
    STRI__MK_CALL("C_ci_test_String8_assignment",     ci_test_String8_assignment,   0),
    STRI__MK_CALL("C_ci_test_UTF8EncodingMarks",      ci_test_UTF8EncodingMarks,    0),
    STRI__MK_CALL("C_ci_test_ListUTF8",                ci_test_ListUTF8,              2),
    STRI__MK_CALL("C_ci_timezone_list",                ci_timezone_list,              2),
    STRI__MK_CALL("C_ci_timezone_set",                 ci_timezone_set,               1),
    STRI__MK_CALL("C_ci_timezone_info",                ci_timezone_info,              3),
    STRI__MK_CALL("C_ci_trans_char",                   ci_trans_char,                 3),
    STRI__MK_CALL("C_ci_trans_isnfc",                  ci_trans_isnfc,                1),
    STRI__MK_CALL("C_ci_trans_isnfd",                  ci_trans_isnfd,                1),
    STRI__MK_CALL("C_ci_trans_isnfkc",                 ci_trans_isnfkc,               1),
    STRI__MK_CALL("C_ci_trans_isnfkd",                 ci_trans_isnfkd,               1),
    STRI__MK_CALL("C_ci_trans_isnfkc_casefold",        ci_trans_isnfkc_casefold,      1),
    STRI__MK_CALL("C_ci_trans_general",                ci_trans_general,              4),
    STRI__MK_CALL("C_ci_trans_list",                   ci_trans_list,                 0),
    STRI__MK_CALL("C_ci_trans_nfc",                    ci_trans_nfc,                  1),
    STRI__MK_CALL("C_ci_trans_nfd",                    ci_trans_nfd,                  1),
    STRI__MK_CALL("C_ci_trans_nfkc",                   ci_trans_nfkc,                 1),
    STRI__MK_CALL("C_ci_trans_nfkd",                   ci_trans_nfkd,                 1),
    STRI__MK_CALL("C_ci_trans_nfkc_casefold",          ci_trans_nfkc_casefold,        1),
    STRI__MK_CALL("C_ci_trans_totitle",                ci_trans_totitle,              2),
    STRI__MK_CALL("C_ci_trans_tolower",                ci_trans_tolower,              2),
    STRI__MK_CALL("C_ci_trans_toupper",                ci_trans_toupper,              2),
    STRI__MK_CALL("C_ci_trans_casefold",               ci_trans_casefold,             1),
    STRI__MK_CALL("C_ci_trim_both",                    ci_trim_both,                  3),
    STRI__MK_CALL("C_ci_trim_left",                    ci_trim_left,                  3),
    STRI__MK_CALL("C_ci_trim_right",                   ci_trim_right,                 3),
    STRI__MK_CALL("C_ci_unescape_unicode",             ci_unescape_unicode,           1),
    STRI__MK_CALL("C_ci_unique",                       ci_unique,                     2),
    STRI__MK_CALL("C_ci_width",                        ci_width,                      1),
    STRI__MK_CALL("C_ci_wrap",                         ci_wrap,                      10),
    // the list must be NULL-terminated:
    STRI__MK_CALL("C_charr_abi_ok",                     C_charr_abi_ok,                   0),
    STRI__MK_CALL("C_charr_icu_init",                   C_charr_icu_init,                 1),
    STRI__MK_CALL("C_charr_icu_version",                C_charr_icu_version,              0),
    STRI__MK_CALL("C_charr_icu_ok",                     C_charr_icu_ok,                   0),
    STRI__MK_CALL("C_charr_icu_smoke",                  C_charr_icu_smoke,                0),
    STRI__MK_CALL("C_charr_icu_bundled",                C_charr_icu_bundled,              0),
    {NULL,                           NULL,                  0}

};


/** Sets ICU data dir
 *
 * @param libpath
 */
void ci_set_icu_data_directory(const char* libpath)
{
    // libpath == "...../libs"      -> "...../libs"
    // libpath == "...../libs/i386" -> "...../libs"
    // libpath == "...../libs/x64"  -> "...../libs"

    string dir(libpath);
    size_t idx = dir.rfind("libs");
    if (idx == string::npos) {
        // this shouldn't happen
        u_setDataDirectory(libpath); // just use the libpath
        return;
    }

    // idx+5 -> if the string is shorter, as many characters as possible are used
    dir = dir.substr(0, idx+4); // 4 == strlen("libs")
    u_setDataDirectory(dir.c_str());
// #ifndef NDEBUG
    // fprintf(stderr, "ICU data directory=%s\n", dir.c_str());
// #endif

    // anyway, if .dat file will not be found,
    // ICU will use system data (may be stub)


    // 1. Examine the contents of the default ICU data shared library.
    //    If it contains data, use that data.
    //    If the data library is empty, a stub library, proceed to the next step.
    // 2. Dynamically load (memory map, typically) a common format (.dat) file
    //    containing the default ICU data.
}


/**
 * Library initialization.
 *
 * R calls this automatically on lib load/attach.
 */
extern "C" void R_init_charr(DllInfo* dll)
{
    R_registerRoutines(dll, NULL, cCallMethods, NULL, NULL);
    R_useDynamicSymbols(dll, (Rboolean)FALSE);
#if defined(R_VERSION) && R_VERSION >= R_Version(3, 0, 0)
    R_forceSymbols(dll, (Rboolean)TRUE);
#endif

    ci_test_init_erroring_altrep(dll);

    const R_CallMethodDef* methods = cCallMethods;
    while (methods->name) {
        R_RegisterCCallable("charr", methods->name, methods->fun);
        methods++;
    }

    methods = ci_callables;
    while (methods->name) {
        R_RegisterCCallable("charr", methods->name, methods->fun);
        methods++;
    }

    if (!SUPPORT_UTF8) {
        /* Rconfig.h states that all R platforms support that */
        Rf_error("R does not support UTF-8 encoding.");
    }
}


#ifndef NDEBUG

#include <unicode/uclean.h>

/**
 * Library cleanup
 */
extern "C" void  R_unload_charr(DllInfo*)
{
    // see http://bugs.icu-project.org/trac/ticket/10897
    // and https://github.com/Rexamine/stringi/issues/78
    u_cleanup();
}

#endif
