# charr-owned file (generated). tools/import-upstream.R must not rename here.
# Generated by tools/import-upstream.R -- do not edit by hand; edit the
# BACKENDS registry in that script and rerun `Rscript tools/import-upstream.R shims`.
#
# Each ci_* symbol is charr's name for the stringi entry point it stands
# in for. Rows with status "stringi" are pass-through wrappers below;
# rows with status "native" are implemented in R/backend-native.R and do
# not appear here. Wrappers (not aliases) on purpose: an error raised
# inside stringi then carries the stri_* call, so error output matches
# upstream stringr exactly.

charr_backend_table <- data.frame(
  stringi = c("stri_detect_fixed", "stri_startswith_fixed", "stri_endswith_fixed",
    "stri_count_fixed", "stri_locate_first_fixed",
    "stri_locate_all_fixed", "stri_extract_first_fixed",
    "stri_extract_all_fixed", "stri_replace_first_fixed",
    "stri_replace_all_fixed", "stri_split_fixed", "stri_sub",
    "stri_sub_all", "stri_length", "stri_c", "stri_flatten",
    "stri_dup", "stri_trim_left", "stri_trim_right", "stri_trim_both",
    "stri_replace_na", "stri_detect_regex", "stri_count_regex",
    "stri_locate_first_regex", "stri_locate_all_regex",
    "stri_extract_first_regex", "stri_extract_all_regex",
    "stri_replace_first_regex", "stri_replace_all_regex",
    "stri_split_regex", "stri_match_first_regex",
    "stri_match_all_regex", "stri_detect_coll", "stri_startswith_coll",
    "stri_endswith_coll", "stri_count_coll", "stri_locate_first_coll",
    "stri_locate_all_coll", "stri_extract_first_coll",
    "stri_extract_all_coll", "stri_replace_first_coll",
    "stri_replace_all_coll", "stri_split_coll", "stri_order",
    "stri_rank", "stri_cmp_equiv", "stri_duplicated",
    "stri_trans_tolower", "stri_trans_toupper", "stri_trans_totitle",
    "stri_count_boundaries", "stri_locate_first_boundaries",
    "stri_locate_all_boundaries", "stri_extract_first_boundaries",
    "stri_extract_all_boundaries", "stri_split_boundaries",
    "stri_wrap", "stri_pad_left", "stri_pad_right", "stri_pad_both",
    "stri_width", "stri_escape_unicode", "stri_conv"),
  charr = c("ci_detect_fixed", "ci_startswith_fixed", "ci_endswith_fixed",
    "ci_count_fixed", "ci_locate_first_fixed", "ci_locate_all_fixed",
    "ci_extract_first_fixed", "ci_extract_all_fixed",
    "ci_replace_first_fixed", "ci_replace_all_fixed", "ci_split_fixed",
    "ci_sub", "ci_sub_all", "ci_length", "ci_c", "ci_flatten",
    "ci_dup", "ci_trim_left", "ci_trim_right", "ci_trim_both",
    "ci_replace_na", "ci_detect_regex", "ci_count_regex",
    "ci_locate_first_regex", "ci_locate_all_regex",
    "ci_extract_first_regex", "ci_extract_all_regex",
    "ci_replace_first_regex", "ci_replace_all_regex", "ci_split_regex",
    "ci_match_first_regex", "ci_match_all_regex", "ci_detect_coll",
    "ci_startswith_coll", "ci_endswith_coll", "ci_count_coll",
    "ci_locate_first_coll", "ci_locate_all_coll",
    "ci_extract_first_coll", "ci_extract_all_coll",
    "ci_replace_first_coll", "ci_replace_all_coll", "ci_split_coll",
    "ci_order", "ci_rank", "ci_cmp_equiv", "ci_duplicated",
    "ci_trans_tolower", "ci_trans_toupper", "ci_trans_totitle",
    "ci_count_boundaries", "ci_locate_first_boundaries",
    "ci_locate_all_boundaries", "ci_extract_first_boundaries",
    "ci_extract_all_boundaries", "ci_split_boundaries", "ci_wrap",
    "ci_pad_left", "ci_pad_right", "ci_pad_both", "ci_width",
    "ci_escape_unicode", "ci_conv"),
  backend = c("stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi", "stringi", "stringi", "stringi",
    "stringi", "stringi", "stringi"),
  stringsAsFactors = FALSE
)

ci_detect_fixed <- function(...) stri_detect_fixed(...)
ci_startswith_fixed <- function(...) stri_startswith_fixed(...)
ci_endswith_fixed <- function(...) stri_endswith_fixed(...)
ci_count_fixed <- function(...) stri_count_fixed(...)
ci_locate_first_fixed <- function(...) stri_locate_first_fixed(...)
ci_locate_all_fixed <- function(...) stri_locate_all_fixed(...)
ci_extract_first_fixed <- function(...) stri_extract_first_fixed(...)
ci_extract_all_fixed <- function(...) stri_extract_all_fixed(...)
ci_replace_first_fixed <- function(...) stri_replace_first_fixed(...)
ci_replace_all_fixed <- function(...) stri_replace_all_fixed(...)
ci_split_fixed <- function(...) stri_split_fixed(...)
ci_sub <- function(...) stri_sub(...)
ci_sub_all <- function(...) stri_sub_all(...)
ci_length <- function(...) stri_length(...)
ci_c <- function(...) stri_c(...)
ci_flatten <- function(...) stri_flatten(...)
ci_dup <- function(...) stri_dup(...)
ci_trim_left <- function(...) stri_trim_left(...)
ci_trim_right <- function(...) stri_trim_right(...)
ci_trim_both <- function(...) stri_trim_both(...)
ci_replace_na <- function(...) stri_replace_na(...)
ci_detect_regex <- function(...) stri_detect_regex(...)
ci_count_regex <- function(...) stri_count_regex(...)
ci_locate_first_regex <- function(...) stri_locate_first_regex(...)
ci_locate_all_regex <- function(...) stri_locate_all_regex(...)
ci_extract_first_regex <- function(...) stri_extract_first_regex(...)
ci_extract_all_regex <- function(...) stri_extract_all_regex(...)
ci_replace_first_regex <- function(...) stri_replace_first_regex(...)
ci_replace_all_regex <- function(...) stri_replace_all_regex(...)
ci_split_regex <- function(...) stri_split_regex(...)
ci_match_first_regex <- function(...) stri_match_first_regex(...)
ci_match_all_regex <- function(...) stri_match_all_regex(...)
ci_detect_coll <- function(...) stri_detect_coll(...)
ci_startswith_coll <- function(...) stri_startswith_coll(...)
ci_endswith_coll <- function(...) stri_endswith_coll(...)
ci_count_coll <- function(...) stri_count_coll(...)
ci_locate_first_coll <- function(...) stri_locate_first_coll(...)
ci_locate_all_coll <- function(...) stri_locate_all_coll(...)
ci_extract_first_coll <- function(...) stri_extract_first_coll(...)
ci_extract_all_coll <- function(...) stri_extract_all_coll(...)
ci_replace_first_coll <- function(...) stri_replace_first_coll(...)
ci_replace_all_coll <- function(...) stri_replace_all_coll(...)
ci_split_coll <- function(...) stri_split_coll(...)
ci_order <- function(...) stri_order(...)
ci_rank <- function(...) stri_rank(...)
ci_cmp_equiv <- function(...) stri_cmp_equiv(...)
ci_duplicated <- function(...) stri_duplicated(...)
ci_trans_tolower <- function(...) stri_trans_tolower(...)
ci_trans_toupper <- function(...) stri_trans_toupper(...)
ci_trans_totitle <- function(...) stri_trans_totitle(...)
ci_count_boundaries <- function(...) stri_count_boundaries(...)
ci_locate_first_boundaries <- function(...) stri_locate_first_boundaries(...)
ci_locate_all_boundaries <- function(...) stri_locate_all_boundaries(...)
ci_extract_first_boundaries <- function(...) stri_extract_first_boundaries(...)
ci_extract_all_boundaries <- function(...) stri_extract_all_boundaries(...)
ci_split_boundaries <- function(...) stri_split_boundaries(...)
ci_wrap <- function(...) stri_wrap(...)
ci_pad_left <- function(...) stri_pad_left(...)
ci_pad_right <- function(...) stri_pad_right(...)
ci_pad_both <- function(...) stri_pad_both(...)
ci_width <- function(...) stri_width(...)
ci_escape_unicode <- function(...) stri_escape_unicode(...)
ci_conv <- function(...) stri_conv(...)
`ci_sub<-` <- function(...) `stri_sub<-`(...)
`ci_sub_all<-` <- function(...) `stri_sub_all<-`(...)
